### ISSUE TITLE
Cannot copy files to platforms/android folder during the build phase

### ISSUE THREAD

**Issue by codeback** [NativeScript/nativescript-dev-webpack#144]
My project uses Firebase and we need to copy google-services.json to platforms/android. 

The problem is that this file is deleted since the _ns-bundle_ command removes the platform folder and adds it again later.

So that, the build process fails with the following error:
```
Execution failed for task ':processF0F1F2F3F4DebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
```
Is there a way to have this file copied during the build phase?
Thanks.

**Comment by codeback** [comment]
@sis0k0 could you please help us with this? We are blocked with this issue :(

Thanks in advanced.

**Comment by sis0k0** [comment]
Hey @codeback,

There's a tracking issue #145 for removing the 'platform remove/add' workaround. Meanwhile, you can try to build your app using the following commands instead of `npm run start-[android/ios]-bundle`:

1. Clean-up the previous builds
```
tns platform remove android/ios
tns platform add android/ios
```
2. Copy the google-services.json file to your platform's folder.

3. Bundle your app with webpack.
For android:
```
./node_modules/.bin/webpack --config=webpack.android.js --progress
```
For ios:
```
./node_modules/.bin/webpack --config=webpack.ios.js --progress
```

4. Build your project with NativeScript cli.
```
tns build android/ios
```

**Comment by codeback** [comment]
With your workaround I can now build the project correctly.

I've just subscribed to the issue #145.

Thank you very much!!
