### ISSUE TITLE
Problem with submitting a webpacked .ipa to the app store

### ISSUE THREAD

**Issue by bnussey** [NativeScript/nativescript-dev-webpack#159]
I'm trying to archive a webpacked .ipa to the app store with`npm run build-ios-bundle -- --release --for-device` but getting the following errors:

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I am able to run the process successfully without webpacking.. 

On the latest version of everything and NativeScript 3.0.

Any ideas whats going on here?

**Comment by bnussey** [comment]
Seems like am able to build from XCode without issues when not using the `-- --release`.

On latest version of everything.

**Comment by spike1292** [comment]
Had the same problem yesterday also ran into provisioning & sass issues. 
Fixed it with switching to fastlane and swichting to cli next. I choose fastlane over `tns appstore` because appstore also uploads the ipa to iTunes connect and I didn't want that yet.

```bash
rm -rf platforms
 # kickoff the sass compiler, didn't run with --bundle. 
tns prepare ios
# saw that the ns-bundle also cleans stuff so to be sure I added this
rm -rf platforms
tns prepare ios --bundle --provision "$PROVISION" --release
npm run webpack --uglify -- --config=webpack.ios.js --progress

# needed this for Jenkins, might help ;)
currentDir=$(basename "$PWD")
# this regex is bases on https://github.com/telerik/mobile-cli-lib/blob/17a506a820016c2ec961c7b0d56c6e0554539900/project-helper.ts#L53
workspace=${currentDir//[^a-zA-Z0-9]/} 

fastlane gym \
    --workspace "platforms/ios/$workspace.xcworkspace" \
    --scheme "$workspace" \
    --output_directory build \
    --output_name app.ipa \
    --export_method app-store \
    --include_bitcode false \
    --clean
```

Note that we are using cli next. We needed the following fix https://github.com/NativeScript/nativescript-cli/pull/2705 because are following https://codesigning.guide
Our runtime & modules are still on 2.5 and we are using Angular 4, sass and nativescript webpack 0.4.2

Hope this helps a little 😉

**Comment by bnussey** [comment]
@spike1292 this is a huge help, thank you!

**Comment by bnussey** [comment]
@spike1292 this was insanely helpful and allowed me submit my app, you are a legend!

**Comment by divyachandana** [comment]
`Build Settings >> User-Defined >>Add >> PODS_ROOT equals ${SRCROOT}/Pods`
[stack overflow pod error solution](https://stackoverflow.com/a/23852613/3327047)
![go85z](https://user-images.githubusercontent.com/5434731/44262329-46883500-a238-11e8-91b0-c06adf840370.png)
