### ISSUE TITLE
Not Watching for file changes

### ISSUE THREAD

**Issue by tettusud** [NativeScript/nativescript-dev-webpack#165]
Hi I have followed the steps and created a sample app, but wehenver i change .ts files webpack is not reloading it.everytime i have to start it using npm run android-ns-bundle
Any idea?
https://docs.nativescript.org/tooling/bundling-with-webpack

`    "start-android-bundle": "npm run ns-bundle --android --start-app ",
`

**Comment by NickIliev** [comment]
@tettusud when working with Webpack you do not have live syncing by design (as Webpack is basically merging all files into one file). The best practice is to develop your application using the core TNS CLI (e.g. like `tns run android`) which will provide your application with live sync and only when you want to bundle your application to install Webpack and use the Webpack commands.

**Comment by milewski** [comment]
there is no way to keep like a two window one for webpack on watch mode generateting the only file that ns will care about, and another with the ns run android?
