### ISSUE TITLE
Webpack looses styles when uglified

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-dev-webpack#24]
## Steps to reproduce
* `tns create Sample --ng`
* Now add for example yellow background to the sample StackLayout
app.component.ts:
```
...
@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
    styleUrls: [ "app.component.css" ]
})
...
```

app.component.css:
```
StackLayout {
    background-color: yellow;
}
```
* `tns install webpack`
* `tns prepare ios --emulator --bundle`
* `tns run ios --emulator --bundle`

Till there all looks correct:
![simulator screen shot nov 12 2016 06 49 46](https://cloud.githubusercontent.com/assets/15932965/20237029/c61fefee-a8a5-11e6-89e3-0b74df4b13fc.png)

Now add the uglification:
* `npm install webpack --save-dev`
* `tns prepare ios --emulator --bundle`
* `tns run ios --emulator --bundle`
* Adjust the webpack config:
webpack.config.js:
```
var bundler = require("nativescript-dev-webpack");
var webpack = require("webpack");

module.exports = bundler.getConfig({
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            comments: false,
            compress: { warnings: false }
        })
    ]
});
```

And there is where the error occurs:
![simulator screen shot nov 12 2016 06 55 22](https://cloud.githubusercontent.com/assets/15932965/20237041/17259c04-a8a6-11e6-87e3-c3895eeb63f8.png)

**Comment by hdeshev** [comment]
I managed to get bundling working with uglification. Turns out there were three issues causing problems:

1. A broken regex that tns-core-modules use to get `View` class names at runtime.
2. A limitation of the Android toolchain that breaks extending native classes in TypeScript
3. Styler implementations usually register property change callbacks using class names. That requires that we exclude prevent uglify from mangling those classes' names.
4. (bonus) The latest ES6 modules effort in nativescript-angular and nativescript-intl breaks with uglifyjs.

I pushed an update to nativescript-dev-webpack that takes care of #3 above and adds a workaround for #2. Fixing #1 will require a release of tns-core-modules, but, to enable easier testing, I pushed an unofficial tns-core-modules@uglify package. That should be enough to test a non-angular app.

We'll take care of angular apps (#4 above) next week by either releasing a fixed ES6 package that can work with Uglify or reverting @next releases to being an ES5 module.

**Comment by vbresults** [comment]
@hdeshev Any idea when #1 will be merged in?

**Comment by vbresults** [comment]
Thanks for correcting all of these issues @hdeshev .  This can be closed now I think?

**Comment by hdeshev** [comment]
Yes, it should be working fine in NS 2.5+

**Comment by vincentpalita** [comment]
Hello there!

@hdeshev any update point 4? 

Thank you
