### ISSUE TITLE
Executing Webpack failed with exit code 2

### ISSUE THREAD

**Issue by halaharr** [NativeScript/nativescript-dev-webpack#431]
Hi,
     I am getting error when I added Webpack to my existing nativescript app. I do have some typescript error  due to importing platform specific files. I have two files xxxx.android.js and xxxx.ios.js and I was importing xxxx. If I comment out all the typescript errors it builds fine. 

Thanks

**Comment by NickIliev** [comment]
@halaharr in [this documentation article](https://docs.nativescript.org/best-practices/bundling-with-webpack#how-nativescript-dev-webpack-works) you can find how to bundle platform-specific files.

Please consider providing detailed information including sample project and error logs when posting an issue, so that we can recreate the issue locally and investigate it.
