### ISSUE TITLE
Why is application css added to the vendor chunk? 

### ISSUE THREAD

**Issue by lambourn** [NativeScript/nativescript-dev-webpack#450]
What is the reasoning behind adding the application css file to the vendor chunk? Shouldn't this be added to the bundle chunk by default as it belongs to the the application?

https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/vendor.nativescript.ts

**Comment by sis0k0** [comment]
It's because the snapshot plugin creates a heap snapshot from the vendor chunk. 'Snapshotting' the application css with nativescript-theme-core in it improves the start up time for android with up to 0.5s. However, we may consider adding the theme to the vendor chunk only if we're building with snapshot enabled.
Please, open a topic in the [forum](https://discourse.nativescript.org/) if you have other questions :)
