### ISSUE TITLE
@ngtools/webpack missing

### ISSUE THREAD

**Issue by berchik** [NativeScript/nativescript-dev-webpack#585]
Running `.\node_modules\.bin\update-ns-webpack --configs --deps` erases `@ngtools/webpack` which is needed. Also, 0.14.1 requires `"@ngtools/webpack": "~6.1.0-beta.1"` 

Thanks.

**Comment by sis0k0** [comment]
Hi @berchik,

Since version 0.14.0 of `nativescript-dev-webpack`, the `@angular-devkit/build-angular` package is added to the project instead of `@ngtools/webpack`.
That package - `@angular-devkit/build-angular` has a dependency to `@ngtools/webpack`.
We changed the behavior of the plugin to make the {N} Angular projects similar to the default web Angular projects, which also depend to `@angular-devkit/build-angular` and not to `@ngtools/webpack` directly.

**Comment by berchik** [comment]
Hi  @sis0k0 
I know, what I'm saying is its not working. After the cleanup and new webpack.config.js is generated, there is an error of @ngtools/webpack not found when compiling with webpack. I was able to compile only after adding it back to package.json

**Comment by sis0k0** [comment]
@berchik, is `@angular-devkit/build-angular` in your package.json?

**Comment by berchik** [comment]
Yes, version 0.7.0-rc.0

**Comment by sis0k0** [comment]
Can you try doing the following:
1. Remove the dependency to `@ngtools/webpack` that you added.
2. Remove node_modules.
3. Remove package-lock.json if you have it in your project.
4. Run `npm install` again.

If it still fails, share here what's the output of this command: `npm ls @ngtools/webpack`.

**Comment by berchik** [comment]
I’ve already tried removing and reinstalling the node_modules folder several times before, however forgot to remove package-lock.json. Now it works.

Thanks Stanimira!
