### ISSUE TITLE
How do I keep static files from node_modules when bundling with webpack?

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-dev-webpack#59]
We're using a couple of nativescript-plugins that include some static files, one of them is `nativescript-webview-interface`.

We need to be able to load the file `nativescript-webview-interface/www/nativescript-webview-interface.js` in our app for interacting with a `webview` (we also have files for the `webview` in a plugin, but `nativescript-webview-interface` is easiest to show the problem).

We've added the files to our `CopyWebpackPlugin` in our `webpack.common.js`, and the files are put into the `platforms/android/src/main/assets/app`-folder as expected, but they're not in the `APK`-file.

What's the best/correct practice here? That works both when we bundle and when we livesync?

I've created an example here: https://github.com/m-abs/tns-webpack-ng2.3/tree/keep-static-files
Our webpack.common.js' copy config: https://github.com/m-abs/tns-webpack-ng2.3/blob/keep-static-files/webpack.common.js#L42-L45

**Comment by vbresults** [comment]
@hshristov I've been wondering the same thing, in regards to importing XML's.  I can register the JS module but how to distribute reusable XML's?

**Comment by hdeshev** [comment]
I just verified this by adding a single `.js` file in my root app folder, and not `require`-ing it anywhere so that it doesn't get bundled (`non-bundled.js`):

```JavaScript
module.exports.test = function() {
    console.log("non-bundled module");
}
```

I then added a copy-webpack-plugin entry for it:

```JavaScript
{ from: "non-bundled.js" },
```

Then added an event handler that would "require" and call the exported function (Note the `global.require` part that will not get mangled by webpack):

```JavaScript
global.require("~/non-bundled").test();
```

This works fine on my end. It should work with the `nativescript-webview-interface` plugin too, if you pass the path to the file in your app folder.

The same solution should also work for any file, XML documents included.
