### ISSUE TITLE
no "livereload" for changes of *.tns.* of sharing project

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-dev-webpack#601]
_From @hafstad on June 12, 2018 21:0_

I've just tried following the installation / usage guide in the readme so I'm using the recommended version of angular cli.

After install I did the following command:
ng new --collection=@nativescript/schematics --name=my-shared-app --shared

And after that I did following inside the newly created project:
tns run ios --bundle --emulator

The app starts in the iOS simulator as expected, but I noticed that changes made in the files with the *.tns.ts are not refreshing the app. 

The console writes:

_File change detected. Starting incremental webpack compilation...
Webpack compilation complete. Watching for file changes.
Webpack build done!
main.ns.ts_

However if I change in other files such *.html the changes are triggering the app to refresh. 

Is this intended behaviour, or am I doing something wrong?  
 

_Copied from original issue: NativeScript/nativescript-schematics#19_

**Comment by iMarwan-k** [comment]
release 0.15.0 crash the app

**Comment by sis0k0** [comment]
@iMarwan-k, can you send stack trace and your package.json?

**Comment by gschora** [comment]
I'm hoping that this is the right place, because I'm having the same issue on an nativescript-vue project:

- created an project from the vue-cli like in quickstart
- created an html-file in the assets folder (in my case a simple file loading google maps)
- added a webview in app.vue where the src property is the created html-file
- google maps is showing fine when i bundle the app with tns run android --bundle, so I know that the reference to the file is working and the html is transfered
- when I change something in the html-file I get this message:
_File change detected. Starting incremental webpack compilation...
Webpack compilation complete. Watching for file changes.
Webpack build done!
Preparing project...
Project successfully prepared (Android)
Successfully transferred map.html on device 192.168.176.102:5555.
Refreshing application on device 192.168.176.102:5555...
Successfully synced application org.nativescript.application on device 192.168.176.102:5555_

but the changes are not shown.

There are only 3 ways I got the changes I've made in the html-file to show in the app.
- when I close the app in the emulator and then save the changes in the html, the app gets restartet and everything works as expected
- when I save the changes in the html, then hit the back button in the emulator, to send the app in the background and when I get the app back in foreground the changes are working
- or when I completely rebundle the app

Same behavior in the preview app on a real device.

So any help would be appreciated.

tns-cli version: 5.3.2
vue-cli version: 3.6.3
