### ISSUE TITLE
No NgModule metadata found for 'AppModule'

### ISSUE THREAD

**Issue by mkinitcpio** [NativeScript/nativescript-dev-webpack#67]
Hi! I tried to build my app with webPack and have issue with it 
[screenshot with issue](https://pp.vk.me/c636627/v636627547/4ce45/URxuwqL_PT4.jpg)

**AppModule**
```
import { NgModule, NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import { NativeScriptModule } from 'nativescript-angular/platform';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { NativeScriptFormsModule } from "nativescript-angular/forms";

import { AppService } from './app.service';
import { AppComponent } from './app.component';
import { AddCardComponent } from './layouts/addCard/addCard.component';
import { LoginComponent } from './layouts/login/login.component';
import { CardComponent } from './layouts/cardLayout/card.component';
import { CardInfoComponent } from './layouts/cardInfo/cardInfo.component';
import { MainComponent } from './layouts/main/main.component';
import { SettingsComponent } from './layouts/settings/settings.component';
import { ProfileComponent } from './layouts/profile/profile.component';

import { DialogContent } from './layouts/main/dialogMenu/dialogContent.component';

import { routes, navigatableComponents } from './app.routing';

@NgModule({
  schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA],
  imports: [
    NativeScriptModule,
    NativeScriptRouterModule,
    NativeScriptFormsModule,
    NativeScriptRouterModule.forRoot(routes)
  ],
  declarations: [
    AppComponent,
    AddCardComponent,
    MainComponent,
    CardComponent,
    LoginComponent,
    CardInfoComponent,
    SettingsComponent,
    ProfileComponent,
    DialogContent,
    ...navigatableComponents
  ],
  providers: [AppService],
  bootstrap: [AppComponent],
  entryComponents: [DialogContent]
})
export class AppModule { }
```

**main.ts**
```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app.module";

platformNativeScriptDynamic().bootstrapModule(AppModule);
```

**Comment by mkinitcpio** [comment]
I resloved problem. I didn't add ngFactory in my app.

**Comment by DanielKucal** [comment]
Hi @mkinitcpio, I'm facing the same issue. What do you mean by adding ngFactory? Shouldn't it be generated in compilation process? How did you solve the problem?

**Comment by sis0k0** [comment]
Hey @DanielKucal,

This can be caused by several reasons. Do you have a `main.aot.ts` file in your `app` folder? If you do, please share your `package.json` and `webpack.config.js` so we can investigate your issue further.

**Comment by DanielKucal** [comment]
@sis0k0, I had to comment out that .aot.ts file (for me it was different name (also changed in package.json)), because it also was breaking compilation down (couldn't find .ngfactory file or something like that). I didn't have webpack.config.js (should I?), just webpack.common.js, webpack.ios.js and webpack.android.js. I have tried everything for whole day, was using deps proposed in README and other repositories and nothing seemed to work, in best cases I was getting just different error... Too bad error handling is so poorly supported in nativescript for now... I finally used the "groceries" example project as my starter, still have no idea what was wrong there (configuration was very similar to [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced)). I'm sorry I can't help more with this issue.

**Comment by sis0k0** [comment]
@DanielKucal, this error is thrown by the @ngtools/webpack plugin used for AoT compilation and, as I said, can be caused by many things in your project. For example:

1. Some of your code is not AoT compilation compatible. Dynamic requires and function calls inside providers are only two things that can break AoT compilation.

2. Some of the external code (plugins, etc.) you are using is not AoT compatible. In that case, you should see the exact name of the module that is causing the error, so probably that's not the problem in your case.

3. The code organization that you have is breaking the logic in the @ngtools/webpack plugin. You need to have a `main.ts` file which is separated from the main module. Alongside that file, you need to have a `main.aot.ts` file which uses the static platform to compile the respective NgFactory module. In your `app/package.json`, your `main` property should be `main.js`. In case you are using different naming, it should follow the same rules. For example:
`app.ts`, `app.aot.ts` and in the `package.json`: 
```
  "main": "app.js"
```

I'll be glad if we can find out what's causing your problem, so we can improve the `nativescript-dev-webpack` plugin to automatically detect such problems and provide better error messages. If it's possible, you can attach your project and we'll debug it and try to find out the problem.

**Comment by dzfweb** [comment]
i was getting the same error:

```
No NgModule metadata found for 'AppModule' #67
```

curiously solved by removing platforms and add again.
