### ISSUE TITLE
The tns-java-classes.js shouldn't be bundled on iOS

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/nativescript-dev-webpack#7]
It is specific for the Android platform now.

**Comment by hdeshev** [comment]
It isn't bundled. It gets configured as a chunk and a separate entry point only if you are building for android.

Now, `tns-java-classes.js` will get copied to the device since it's stored in the app root. The current `--bundle` behavior will delete just `tns_modules` and preserve the rest of the files.

**Comment by hdeshev** [comment]
Closing in favor of #13
