### ISSUE TITLE
Platform specific templateUrls result in ERROR in ENOENT: no such file or directory on these.

### ISSUE THREAD

**Issue by bnussey** [NativeScript/nativescript-dev-webpack#75]
As I understand it, this plugin now correctly identifies platform specific css, so `welcome.component.ios.css` and `welcome.component.android.css` will be compiled. However in our project we also have platform specific platform templateUrls, so `welcome.component.ios.html` and `welcome.component.android.html` but at present this is resulting in `ERROR in ENOENT: no such file or directory on these.`

Is it possible to get support in place for platform specific templateUrls?

Thanks

**Comment by hdeshev** [comment]
There are no plans to support platform-specific templates at the moment. There is an easy workaround though: use the `<android>` and `<ios>` component tags in your template to separate platform-specific markup.

I know this doesn't sound too good, especially since it requires that you modify your app, but I think we should be focusing our effort and limiting support for "extra" features like this one. The plugin has already grown to be very complex and syncing with every ngtools release is very very painful.

**Comment by bnussey** [comment]
Hey @hdeshev completely understand your position on this.. was just wondering if the same code for styleUrls could be leveraged though to make this quite simple?

**Comment by bnussey** [comment]
Hey @sis0k0 so this has been resolved for templateUrls?

**Comment by sis0k0** [comment]
Sorry, closed the wrong issue..

**Comment by bnussey** [comment]
No worries, was a bit confused after checking the commits. For anyone having same problem, i just created a bash script to automate changing the filenames back and forth. Works great.

**Comment by EddyVerbruggen** [comment]
@bnussey I like your workaround, but I'd also rather see this supported our of the box as {N} supports using `.ios`/`.android` extensions in view files, so it would be very convenient if webpack plays nice with that convention. Hence I opened PR #155.

**Comment by bnussey** [comment]
I agree 100% @EddyVerbruggen
