### ISSUE TITLE
HMR: Hot-updates generated for unchanged file

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-dev-webpack#877]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: `5.3.4`
 - Cross-platform modules: `5.3.1`
 - Android Runtime: `5.3.1`
 - iOS Runtime:`5.3.1`
 - Node.js: `10.15.1`
 - nativescript-dev-webpack: `~0.21.0`

**Describe the bug**
HMR generates hot-updates for files that are not changed.

**To Reproduce**

1. Create and run with HMR
```
tns create test-app --tsc
cd test-app
tns run ios --hmr
```
2. Change and save `main-view-modes.ts` file multiple times to generate hot updates.

Explore the generated hot-updates in `platforms/ios/testapp/app/`( the  `bundle.XXXX.hot-update.js` files). All of them (except the first update) contain both `main-view-modes.ts` **and `./main-page.ts`**. 
The `./main-page.ts` file wasn't changed, so it should not be re-generated and sent as a hot-update.

**Expected behavior**
Changes should be generated only for the changed files.

**Why This Is Important**
In the above example trying to use `module.hot.accept(["./main-view-model"], () => { ... })` and handle view-model changes inside `main-page.ts` is not possible. Because the `main-page.ts` is also included in the hot-update it's changes bubble up and cannot be handled.

**Possible Cause and Solution**
According to [ts-loader docs](https://github.com/TypeStrong/ts-loader#hot-module-replacement) the `transpileOnly` flag should be enabled when using the loader with HMR.

Indeed setting `transpileOnly: true` in the `ts-loader` resolves the issue.

**Comment by vakrilov** [comment]
Acceptance criteria:

-  Check that after changing multiple times `main-view-model.ts` the generated hot-updates (`bundle.XXXX.hot-update.js`) do not contain `"main-page.ts"`
- Check that after causing type error in TypeScript - the error is shown on the console. Example code that should cause the error `main-page.ts`:
```
page.bindingContext = new HelloWorldModel("test");
```
Should cause `Expected 0 arguments, but got 1.` error.

**Comment by webleaf** [comment]
seems like `transpileOnly` option make impossible to use `const enum`
https://github.com/Microsoft/TypeScript/issues/16671#issuecomment-344449974

**Comment by DimitarTachev** [comment]
@webleaf,

By using `transpileOnly: false`, the enums are inlined compile time. In other words, `color: Colors.red` is directly replaced with `color: "red"` in your JavaScript code and you don't need the `Colors` enum available and exported in the JavaScript modules.

However, `transpileOnly: true` is not making impossible to use the `const enums`, it just does **not inline** them. In other words, you have to **export** the enums in order to make them available at runtime because in your JavaScript code you will still have `color: Colors.red` and the `Colors` enum should be available and exported in the JavaScript modules.
