### ISSUE TITLE
Android Back Button Event Not Working

### ISSUE THREAD

**Issue by alexZaicev** [NativeScript/nativescript-dev-webpack#909]
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 5.4.0 version and is up to date.

Describe the bug
Application event subscriber does not work for android back button pressed event. I have tried with Legacy and it works fine, however it does not with Webpack workflow

To Reproduce
To see it working with legacy:
tns run android --no-bundle
To see it not working webpack:
tns run android --hmr

Expected Behavior
I should be able to subscribe on back pressed event and override the behavior for different layout components

Sample project
Demo repository is created:
[LINK](https://github.com/alexZaicev/nativescript-backbutton-bug)

**Comment by alexZaicev** [comment]
Are there any updates on this issue?

**Comment by rosen-vladimirov** [comment]
Hey @alexZaicev ,
Thanks for the sample project. We've investigated it and we've noticed the event is actually raised correctly. The problem arises in the event handler itself, where you check the `currentPage.exports`. In order to receive correct context there, i.e. `currentPage.exports.onBackPressed` to be available, you can define the function in `main-page.ts` as:
```TypeScript
export const onBackPressed = (e: any) => {
	e.cancel = true;
	const pg: Page = topmost().currentPage;
	const vm: HelloWorldModel = pg.bindingContext;
	vm.onGoBack();
}
```

This way webpack will export the function in the context, so it will be available in the `currentPage.exports` object. 
Can you give it a try and see if it works on your side?

**Comment by alexZaicev** [comment]
@rosen-vladimirov Thanks, I make it work, however, when I put breakpoint on the event callback in Chrome debugger it`s not hit on the back press...
