### ISSUE TITLE
Vue app crashes after sync changes in styles

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-dev-webpack#943]
**Environment**
 - CLI: next(6.0)
 - Cross-platform modules:6.0.0-next-2019-06-17-201500-04 
- Android Runtime:6.0.0-2019-06-13-112614-01
 - iOS Runtime:6.0.0-2019-06-13-141312-01
 - Plugin(s):nativescript-vue@2.3.0-rc.0

**Describe the bug**
When making changes in styles section of Home.vue file app crashes

**To Reproduce**
1. tns create TestApp --vue
2. npm i tns-core-modules@next --save
3. npm i nativescript-dev-webpack@next --save-dev 
4. node_modules/.bin/update-ns-webpack --deps --configs
5. npm i NativeScript-vue@next
6 .tns platform add ios@next
7. tns run iOS
8. In Home.vue in style section in .info style (line39), add color:red;

**Expected behavior**
Project is synced and style is applied.

**Actual**
Project is synced but crashes. Log:
[log_file.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/3311015/log_file.txt)

**Additional context**
Make exactly that change in the file

**Comment by vchimev** [comment]
Hey @rigor789,

do you have any idea why [`global.__onLiveSyncCore()`](https://github.com/nativescript-vue/nativescript-vue/blob/v2.2.2/platform/nativescript/framework.js#L61-L72) does not execute in version **2.3.0-rc.0**? It works fine with **2.2.2**.

Thanks,

**Comment by vchimev** [comment]
Hey!

This issue is caused by a [change](https://github.com/nativescript-vue/nativescript-vue/commit/e983a90e484f964e6561477711a5c991cfac86c3#diff-cf2adfc1b09d7cc80a78107c9abedfa0R41) in the `nativescript-vue` plugin.

In version 2.3.0-rc.0, the `global.__onLiveSyncCore` overwrite function requires the `tns-core-modules/application` module which contains the `global.__onLiveSyncCore` logic itself.
As a result, the overwrite function doesn't serve its purpose.

A solution could be to require the `tns-core-modules/application` module in the global scope [here](https://github.com/nativescript-vue/nativescript-vue/blob/v2.3.0-rc.0/platform/nativescript/runtime/index.js#L53).
@rigor789 and @vakrilov, what are your opinions on the approach to handle the livesync logic?

**Comment by vakrilov** [comment]
Sounds like an easy fix. 
We have a similar case in [nativescript-angular package and we make sure we require polyfills and application first](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L1-L4).

**Comment by endarova** [comment]
I can confirm the issue is resolved in nativescript-vue@next

**Comment by endarova** [comment]
Actually the  issue for iOS is fixed but now when I make the same change for android the app crashes again. Here is the log 
[log.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/3353569/log.txt)
